### ISSUE TITLE
Error on require (npm)

### ISSUE THREAD

**Issue by dbilovd** [zenorocha/clipboard.js#115]
I get the following error when I require clipboard module in my module.

`ReferenceError: Element is not defined
    at Object.<anonymous> (.../clipboard/node_modules/good-listener/node_modules/delegate/node_modules/closest/node_modules/matches-selector/index.js:6:13)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (.../clipboard/node_modules/good-listener/node_modules/delegate/node_modules/closest/index.js:1:77)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
`

It seems it comes from `matches-selector` module.

Don't know if it's unique to me or someone else has encountered this issue before?

**Comment by zenorocha** [comment]
Hey @dbilovd, what version are you fetching? Make sure you fetch `v1.5.3` because it fixes a problem with npm.

**Comment by dbilovd** [comment]
Hi @zenorocha should it be specifically 1.5.3? My package.json file is set to '^1.5.3' so do I have to force it to use '1.5.3' and no newer version?

**Comment by kafeltz** [comment]
sometimes destroying node_modules folder and start over it again works (happened to me already in other project)

**Comment by dbilovd** [comment]
Thanks @kafeltz I'll give that a try.

**Comment by startupthekid** [comment]
I ran into this problem when I was using server-side rendering with React & Redux. Basically any library that had browser specific code, such as `window` or `document` would fail because they'd be undefined in the node environment.

You can do one of two things, either shim the necessary objects (`window = typeof window === 'undefined' ? {} : window`, that sort of thing) or just wrap the require in an if statement:

```
let Clipboard;
if (typeof window !== 'undefined') {
    Clipboard = require('clipboard');
}

**Comment by kafeltz** [comment]
I still think it's weird using some libs in node environments.

**Comment by zenorocha** [comment]
You can also use the unofficial react wrappers:

* https://www.npmjs.com/package/react-clipboard.js
* https://www.npmjs.com/package/react-clip
