### ISSUE TITLE
Errors when copying

### ISSUE THREAD

**Issue by Alex-Sokolov** [zenorocha/clipboard.js#357]
### Minimal example

https://jsfiddle.net/gtv0s2ht/3/

### Expected behaviour

Clipboard.js can choose element by ID or class. And copying must be without errors in console

### Actual behaviour

Error in console:
```
Uncaught DOMException: Failed to execute 'querySelector' on 'Document': '#123' is not a valid selector.
    at e.t (https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/1.5.10/clipboard.min.js:7:9566)
    at e.t [as onClick] (https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/1.5.10/clipboard.min.js:7:9372)
    at HTMLBodyElement.<anonymous> (https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/1.5.10/clipboard.min.js:7:9164)
    at HTMLBodyElement.<anonymous> (https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/1.5.10/clipboard.min.js:7:1175)
```
or by second button:
```
Uncaught DOMException: Failed to execute 'webkitMatchesSelector' on 'Element': '#4324324' is not a valid selector.
    at o (https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/1.5.10/clipboard.min.js:7:2554)
    at e.exports (https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/1.5.10/clipboard.min.js:7:869)
    at HTMLBodyElement.<anonymous> (https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/1.5.10/clipboard.min.js:7:1138)
```

### Browsers affected

Using Google Chrome 56.0.2924.28 beta (64-bit)

**Comment by komarevtsevdn** [comment]
I have a same problem.

**Comment by Alex-Sokolov** [comment]
But there are perfectly valid selectors. This is a bug

**Comment by ajcrites** [comment]
This is part of the document selectors API which is throwing the error that it's not a valid selector so it can't be fixed by this library without special handling.

However, this is _not_ a valid selector as selectors (CSS identifiers) [cannot start with a number](https://www.w3.org/TR/CSS21/syndata.html#value-def-identifier)

The attribute is valid, but it's not a valid selector.
