### ISSUE TITLE
Error: Cannot find module './closest'

### ISSUE THREAD

**Issue by brandonros** [zenorocha/clipboard.js#457]
test.js

```
require('./bower_components/clipboard/dist/clipboard.js');
```

`$ browserify test.js -o bundle.js`

```
Error: Cannot find module './closest' from '/Users/foo/project/bower_components/clipboard/dist'
    at /Users/foo/.nvm/versions/node/v7.9.0/lib/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:55:21
    at load (/Users/foo/.nvm/versions/node/v7.9.0/lib/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/Users/foo/.nvm/versions/node/v7.9.0/lib/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /Users/foo/.nvm/versions/node/v7.9.0/lib/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:114:15
```

**Comment by tkdan235** [comment]
fwiw I am seeing another dependency error occasionally as well when trying to use `clipboard.js` via `bower`.

```
events.js:163
      throw er; // Unhandled 'error' event
      ^

Error: module "./is" not found from "/Users/foo/Projects/app/vendor/clipboard/dist/clipboard.js"
```

**Comment by tkdan235** [comment]
I attempted to load the project from the cdn url instead and ran into the same issue:

```
events.js:163
      throw er; // Unhandled 'error' event
      ^

Error: module "./closest" not found from "/Users/foo/Projects/app/vendor/clipboard/dist/clipboard.js"
  at notFound (/Users/foo/Projects/app/node_modules/browserify/index.js:812:15)
```

**Comment by zenorocha** [comment]
Hmmm, no changes were made over here. By the way, did you see that Bower is going away?

<img width="991" alt="screen shot 2017-08-09 at 1 08 31 pm" src="https://user-images.githubusercontent.com/398893/29143090-ded09f56-7d08-11e7-8102-2de5e6a82f82.png">

**Comment by tkdan235** [comment]
Heh yeah I'm going to have to move bower out of the stack. =)

I did try using yarn to load `clipboard.js` as well and encountered the same `Error: Cannot find module './closest'`.  I suspect there is some downstream dep issue.

I ended up using the cdn hosted script which turned out to work fine.
