### ISSUE TITLE
Copy action failed intermittently

### ISSUE THREAD

**Issue by lau2468** [zenorocha/clipboard.js#557]
I used this plugin with leaflet. I have the leaflet popup text dynamically generate a texarea and a button which I want to use Clipboard.js to copy the contents. The copy worked fine most of the time but sometimes it fails. I have no idea the different between fail and success. It looks like random.

All js libraries that I used within my page

        <script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.0/clipboard.min.js"></script>
  
         <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
        <script src="https://netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
        <link href="https://netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" 
       rel="stylesheet"/>
       <script src="Scripts/jquery.easy-autocomplete.min.js"></script>

Here is my code to generate the textbox and button:

        clipboard = new ClipboardJS('.btn');
        function popupText(name, boss, level, action, expire, uuid, exEli) {
	var text = "<textarea id=\"" + uuid + "\" rows=\"5\" cols=\"50\" readonly style=\"resize: none; 
        border: none;\">" + name+ "&#13;" + boss + " :" + level + "&#13;" + action + " at " + expire + 
        "&#13;" +
        "https://mywebsite.ca/go/?event=" + uuid + "&#13;" + exEli + "</textarea>" +
        "<button class=\"btn btn-primary\" data-clipboard-action=\"copy\" data-clipboard-target=\"#" 
        + 
        uuid + "\"><img class=\"clippy\" src=\"Resources/clippy.svg\" width=\"13\" alt=\"Copy to 
        clipboard\"></button>";
       return text;		
      }

Error message is like this:

        Uncaught DOMException: Failed to execute 'querySelector' on 'Document': '#8GRBC' is not a valid selector.
    at e.value [as target] (https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.0/clipboard.min.js:7:8239)
    at e.value (https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.0/clipboard.min.js:7:8017)
    at HTMLBodyElement.<anonymous> (https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.0/clipboard.min.js:7:7809)
    at HTMLBodyElement.<anonymous> (https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.0/clipboard.min.js:7:9598)

**Comment by lau2468** [comment]
Sorry, I should have read the previous issue. The id cannot start with numeric character.
