### ISSUE TITLE
Error syntax occurred when compress

### ISSUE THREAD

**Issue by khoakmf2016** [zenorocha/clipboard.js#573]
Error syntax occurred when I  compress with this command below
 java -jar yuicompressor-2.4.8.jar --nomunge  clipboard.min.js

### Expected behaviour
Can compress this file.

### Actual Result
[ERROR] in clipboard.min.js
  7:588:missing name after . operator
[ERROR] in clipboard.min.js
  7:633:missing : in conditional expression
[ERROR] in clipboard.min.js
  7:1015:invalid property id
[ERROR] in clipboard.min.js
  7:1282:missing ; before statement
[ERROR] in clipboard.min.js
  7:1412:missing ) after argument list
[ERROR] in clipboard.min.js
  7:2691:missing name after . operator
[ERROR] in clipboard.min.js
  7:4411:missing ; before statement
[ERROR] in clipboard.min.js
  7:4432:syntax error
[ERROR] in clipboard.min.js
  7:4688:invalid return
[ERROR] in clipboard.min.js
  7:4721:invalid return
[ERROR] in clipboard.min.js
  7:4752:invalid return
[ERROR] in clipboard.min.js
  7:4858:syntax error
[ERROR] in clipboard.min.js
  7:5222:syntax error
[ERROR] in clipboard.min.js
  7:5316:invalid return
[ERROR] in clipboard.min.js
  7:5442:invalid return
[ERROR] in clipboard.min.js
  7:5617:invalid return
[ERROR] in clipboard.min.js
  7:5766:invalid return
[ERROR] in clipboard.min.js
  7:6026:invalid property id
[ERROR] in clipboard.min.js
  7:7776:missing name after . operator
[ERROR] in clipboard.min.js
  7:7981:missing name after . operator
[ERROR] in clipboard.min.js
  7:8721:missing name after . operator
[ERROR] in clipboard.min.js
  7:8736:syntax error
[ERROR] in clipboard.min.js
  7:8791:syntax error
[ERROR] in clipboard.min.js
  7:8862:syntax error
[ERROR] in clipboard.min.js
  7:9083:syntax error
[ERROR] in clipboard.min.js
  7:9159:invalid return
[ERROR] in clipboard.min.js
  7:9631:syntax error
[ERROR] in clipboard.min.js
  7:9796:invalid return
[ERROR] in clipboard.min.js
  7:10534:invalid return
[ERROR] in clipboard.min.js
  1:0:Compilation produced 29 syntax errors.
org.mozilla.javascript.EvaluatorException: Compilation produced 29 syntax errors.
        at com.yahoo.platform.yui.compressor.YUICompressor$1.runtimeError(YUICompressor.java:172)
        at org.mozilla.javascript.Parser.parse(Parser.java:396)
        at org.mozilla.javascript.Parser.parse(Parser.java:340)
        at com.yahoo.platform.yui.compressor.JavaScriptCompressor.parse(JavaScriptCompressor.java:315)
        at com.yahoo.platform.yui.compressor.JavaScriptCompressor.<init>(JavaScriptCompressor.java:536)
        at com.yahoo.platform.yui.compressor.YUICompressor.main(YUICompressor.java:147)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at com.yahoo.platform.yui.compressor.Bootstrap.main(Bootstrap.java:21)

Thanks for your help!

**Comment by Ruffio** [comment]
Why do you try to compress an already compressed file? clipboard.min.js is already compress, hence the min in the file name. Use the non-compressed version instead: clipboard.js

**Comment by zenorocha** [comment]
Thanks @Ruffio for assisting on the issues!
