### ISSUE TITLE
latest build (2.0.3) will break server side render

### ISSUE THREAD

**Issue by kovenliao** [zenorocha/clipboard.js#598]
### Minimal example

```
$ node
> require ('./dist/clipboard.js')
ReferenceError: window is not defined
    at Object.<anonymous> (/Users/kovenliao/0_work/git/clipboard.js/dist/clipboard.js:16:4)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at repl:1:1
    at sigintHandlersWrap (vm.js:22:35)
```

reference:
https://stackoverflow.com/questions/49111086/webpack-4-universal-library-target
https://github.com/webpack/webpack/issues/6525

### Expected behavior
should work in both node.js and browser

**Comment by zenorocha** [comment]
Fixed at 2.0.4, thanks for reporting!
