### ISSUE TITLE
Regression in 2.0.9 leading to values other than type string (number, boolean) cannot be copied

### ISSUE THREAD

**Issue by tasso94** [zenorocha/clipboard.js#873]
## 🐛 Bug Report

See the following example:

```javascript
new ClipboardJS(document.getElementsByClassName("btn"), {
  text: function() {
    return 900;
  }
});
```

### Expected Behaviour

When text() returns another value type than string, no error is shown and value is stored in the clipboard.

### Actual Behaviour

When text() returns another value type than string, the following error is shown:

```
Uncaught TypeError: element.hasAttribute is not a function
    at select (clipboard.js:717:1)
    at ClipboardActionCopy (clipboard.js:117:1)
    at ClipboardActionDefault (clipboard.js:166:1)
    at Clipboard.onClick (clipboard.js:290:1)
    at HTMLAnchorElement.<anonymous> (clipboard.js:278:1)
```

### To Reproduce

Check out the following JS Riddle: https://jsfiddle.net/L6ptjo7w/

### Browsers Affected

I tested it on Chrome 123.

### Operational System

Mac OS Ventura.

**Comment by obetomuniz** [comment]
Thanks for reporting this @tasso94. And thanks to provide a reproducible environment. I'm planning to contribute to some open issues soon. I will be triaging it. Thanks again.

**Comment by tasso94** [comment]
Hi @obetomuniz,

That would be awesome. Thanks 👍
